print('北京')
print('欢迎你')
print('----------')
print('北京\n欢迎你')
print('北\n京\n欢\n迎\n你')
print('-----------')
print('北京北京北京\t欢迎你')
print('hello\toooo')
print('hellooooo')
print('老师说：\'好好学习，天天向上\'')
print('老师说：\"好好学习，天天向上\"')

print(r'北\n京\n欢\n迎\n你')
print(R'北\n京\n欢\n迎\n你')