print('-'*50)
print('123'.isdigit())
print('一二三'.isdigit())
print('0b1010'.isdigit())
print('ⅠⅠⅠⅠⅠⅠⅠ'.isdigit())

print('-'*50)
print('123'.isnumeric())
print('一二三'.isnumeric())
print('0b1010'.isnumeric())
print('ⅠⅠⅠⅠⅠⅠⅠ'.isnumeric())
print('壹贰叁'.isnumeric())

print('-'*50)
print('hello你好'.isalpha())
print('hello你好123'.isalpha())
print('hello你好123一二三'.isalpha())
print('hello你好123ⅠⅠⅠⅠⅠⅠⅠ'.isalpha())

print('-'*50)
print('hello你好'.isalnum())
print('hello你好123'.isalnum())
print('hello你好123一二三'.isalnum())
print('hello你好123ⅠⅠⅠⅠⅠⅠⅠ'.isalnum())

print('-'*50)
print('HelloWorld'.islower())
print('helloworld'.islower())
print('hello您好'.islower())
print('hello一二三'.islower())

print('-'*50)
print('HelloWorld'.isupper())
print('HELLOWORLD'.isupper())
print('HELLO您好'.isupper())
print('HELLO壹贰叁'.isupper())

print('-'*50)
print('Hello'.istitle())
print('HelloWorld'.istitle())
print('Helloworld'.istitle())
print('Hello World'.istitle())
print('Hello world'.istitle())

print('-'*50)
print('\t'.isspace())
print(' '.isspace())
print('\n'.isspace())